### ISSUE TITLE
Encoding issue in parser.replace_base_url function

### ISSUE THREAD

**Issue by keithminuszero** [fabiocaccamo/django-freeze#117]
**Python version**
3.9

**Django version**
3.2.15

**Package version**
0.10.0

**Current behavior (bug description)**
I am receiving the following error upon attempting to generate_static_site from the management command:
```
# docker compose -f local.yml exec django /entrypoint python manage.py generate_static_site
PostgreSQL is available
INFO 2024-03-01 20:26:51,545 scanner 447 139998567057216 fetch urls...
INFO 2024-03-01 20:26:51,558 scanner 447 139998567057216 
fetch url: http://django:8000/
INFO 2024-03-01 20:26:51,853 scanner 447 139998567057216 [OK]
Traceback (most recent call last):
  File "/app/manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.9/site-packages/freeze/management/commands/generate_static_site.py", line 12, in handle
    scanner.scan(),
  File "/usr/local/lib/python3.9/site-packages/freeze/scanner.py", line 171, in scan
    scan_url(url)
  File "/usr/local/lib/python3.9/site-packages/freeze/scanner.py", line 135, in scan_url
    file_data = parser.replace_base_url(html, file_base_url)
  File "/usr/local/lib/python3.9/site-packages/freeze/parser.py", line 123, in replace_base_url
    text = text.replace("/" + media_url, media_url)
TypeError: a bytes-like object is required, not 'str'
```
It looks to me like this comes from [this line](https://github.com/fabiocaccamo/django-freeze/blob/ff1b98559f8d57e55627b13290e869d4b56b13fb/freeze/scanner.py#L104) that encodes the content to utf-8. 

I am confused about why that encoding happens before further string operations. My media_url and base_url variables are strings.

**Expected behavior**
No error.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/fabiocaccamo) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/fabiocaccamo/django-freeze/issues/117">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/fabiocaccamo/django-freeze/issues/117/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/fabiocaccamo/django-freeze/issues/117/pledge.svg">
</picture>
</a>

**Comment by fabiocaccamo** [comment]
Fixed in `0.11.0` version.
